name: kdl
version: 1.0.0
description: Dart implementation of the KDL Document Language
repository: https://github.com/danini-the-panini/kdl-dart
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  big_decimal: ^0.3.1
  string_scanner: ^1.1.0
  punycode: ^1.0.0
dev_dependencies:
  test: ^1.19.5
  path: ^1.8.0
