name: kdl
version: 1.0.1
description: Dart implementation of the KDL Document Language
repository: https://github.com/danini-the-panini/kdl-dart
environment:
  sdk: ">=3.0.0 < 4.0.0"
dependencies:
  big_decimal: ^0.5.0
  string_scanner: ^1.2.0
dev_dependencies:
  test: ^1.25.2
  path: ^1.9.0
