name: kdl
version: 1.0.0+1
description: Dart implementation of the KDL Document Language
repository: https://github.com/danini-the-panini/kdl-dart
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  big_decimal: ^0.5.0
  string_scanner: ^1.1.1
dev_dependencies:
  test: ^1.21.4
  path: ^1.8.0
